#!/bin/sh
cd /mnt/c/Users/ayden/Desktop/Workspace/MirrorsRemote/dpm-20261004/normal-v3/build || exit 98
exec /mnt/c/Users/ayden/Desktop/Workspace/MirrorsRemote/dpm-20261004/normal-v3/build/dpm_native_worker.exe
