import Shell.ModelInterface.Emit.TypeScript

namespace Shell.ModelInterface.Emit.SuiteNativeRuntime

/-- Gate-free Node-native conversion emitted only in suite companions. -/
def source : String := String.intercalate "\n" [
  "function frozen<T>(value: T): T {",
  "  if (value !== null && typeof value === \"object\" && !Object.isFrozen(value)) {",
  "    for (const child of Object.values(value)) frozen(child);",
  "    Object.freeze(value);",
  "  }",
  "  return value;",
  "}",
  "",
  "function record(value: unknown, names: readonly string[]): Record<string, unknown> {",
  "  if (value === null || typeof value !== \"object\" || Array.isArray(value) ||",
  "      (Object.getPrototypeOf(value) !== null && Object.getPrototypeOf(value) !== Object.prototype)) {",
  "    throw new TypeError(\"Expected a plain closed record\");",
  "  }",
  "  const keys = Reflect.ownKeys(value);",
  "  if (keys.length !== names.length || keys.some(key => typeof key !== \"string\" || !names.includes(key))) {",
  "    throw new TypeError(\"Record fields do not match the public contract\");",
  "  }",
  "  for (const name of names) {",
  "    const property = Object.getOwnPropertyDescriptor(value, name);",
  "    if (!property || !(\"value\" in property)) throw new TypeError(\"Expected an own data field\");",
  "  }",
  "  return value as Record<string, unknown>;",
  "}",
  "",
  "type Converted = { readonly value: unknown; readonly key: string };",
  "",
  "// A canonical semantic key, independent of insertion order and object identity,",
  "// also makes composite set duplicates fail before any application operation.",
  "export function convertNativeValue(type: ModelType, value: unknown, toNative: boolean, depth = 0): Converted {",
  "  if (depth > 128) throw new TypeError(\"Native value nesting limit exceeded\");",
  "  const convert = (shape: ModelType, item: unknown): Converted => convertNativeValue(shape, item, toNative, depth + 1);",
  "  const result = (item: unknown, key: unknown): Converted => ({value: item, key: JSON.stringify(key)});",
  "  switch (type.kind) {",
  "    case \"int\": if (typeof value === \"bigint\") return result(value, [\"int\", value.toString()]); break;",
  "    case \"bool\": if (typeof value === \"boolean\") return result(value, [\"bool\", value]); break;",
  "    case \"str\": if (typeof value === \"string\") return result(value, [\"str\", value]); break;",
  "    case \"null\": if (value === null) return result(null, [\"null\"]); break;",
  "    case \"seq\": case \"tuple\": case \"set\": {",
  "      const values = type.kind === \"set\" && !toNative",
  "        ? (value instanceof Set ? [...value] : null)",
  "        : (Array.isArray(value) ? value : null);",
  "      if (!values || (type.kind === \"tuple\" && values.length !== type.elements.length)) break;",
  "      const converted: Converted[] = [];",
  "      for (let index = 0; index < values.length; index++) {",
  "        if (!Object.hasOwn(values, index)) throw new TypeError(\"Sparse arrays are unsupported\");",
  "        converted.push(convert(type.kind === \"tuple\" ? type.elements[index]! : type.element, values[index]));",
  "      }",
  "      const keys = converted.map(item => item.key);",
  "      if (type.kind === \"set\" && new Set(keys).size !== keys.length) throw new TypeError(\"Duplicate semantic set element\");",
  "      const items = converted.map(item => item.value);",
  "      return result(type.kind === \"set\" && toNative ? new Set(items) : items,",
  "        [type.kind, type.kind === \"set\" ? keys.sort() : keys]);",
  "    }",
  "    case \"map\": {",
  "      if (type.key.kind !== \"str\") throw new TypeError(\"Only string map keys are supported\");",
  "      const entries = toNative ? (Array.isArray(value) ? value : null) : (value instanceof Map ? [...value] : null);",
  "      if (!entries) break;",
  "      const seen = new Set<string>();",
  "      const converted: [string, unknown][] = [];",
  "      const keys: [string, string][] = [];",
  "      for (const entry of entries) {",
  "        if (!Array.isArray(entry) || entry.length !== 2 || typeof entry[0] !== \"string\" || seen.has(entry[0])) {",
  "          throw new TypeError(\"Invalid or duplicate map key\");",
  "        }",
  "        seen.add(entry[0]);",
  "        const item = convert(type.value, entry[1]);",
  "        converted.push([entry[0], item.value]);",
  "        keys.push([entry[0], item.key]);",
  "      }",
  "      keys.sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0);",
  "      return result(toNative ? new Map(converted) : converted, [\"map\", keys]);",
  "    }",
  "    case \"record\": {",
  "      const source = record(value, type.fields.map(field => field.wireName));",
  "      const fields = [...type.fields].sort((a, b) => a.wireName < b.wireName ? -1 : a.wireName > b.wireName ? 1 : 0);",
  "      const converted = fields.map(field => [field.wireName, convert(field.type, source[field.wireName])] as const);",
  "      return result(Object.fromEntries(converted.map(([name, item]) => [name, item.value])),",
  "        [\"record\", converted.map(([name, item]) => [name, item.key])]);",
  "    }",
  "    case \"variant\": {",
  "      const source = record(value, [\"tag\", \"value\"]);",
  "      const selected = type.cases.find(item => item.tag === source.tag);",
  "      if (!selected) throw new TypeError(\"Unknown declared variant\");",
  "      const payload = convert(selected.payload, source.value);",
  "      return result({tag: selected.tag, value: payload.value}, [\"variant\", selected.tag, payload.key]);",
  "    }",
  "    case \"opaqueItf\": throw new TypeError(\"Opaque values are unsupported\");",
  "  }",
  "  throw new TypeError(\"Value does not match public type \" + type.kind);",
  "}",
  "",
  "function nativePublicPort(candidate: unknown, manifest: SuitePublicManifest): SuitePublicPort {",
  "  if (candidate === null || typeof candidate !== \"object\") throw new TypeError(\"Expected a native adapter\");",
  "  const adapter = candidate as NativeSuiteAdapter;",
  "  const operations = [...manifest.initializers, ...manifest.actions];",
  "  const handlers = record(adapter.actions, operations.map(operation => operation.id));",
  "  for (const operation of operations) {",
  "    if (typeof handlers[operation.id] !== \"function\") throw new TypeError(\"Missing native operation \" + operation.id);",
  "  }",
  "  if (typeof adapter.observe !== \"function\") throw new TypeError(\"Missing native observer\");",
  "  // Capture admitted functions so later adapter mutation cannot replace a handler.",
  "  const admitted = Object.fromEntries(operations.map(operation => [operation.id, handlers[operation.id]])) as NativeSuiteAdapter[\"actions\"];",
  "  const observe = adapter.observe.bind(adapter);",
  "  return {",
  "    async invoke(operationId, inputs, context) {",
  "      const operation = operations.find(item => item.id === operationId);",
  "      if (!operation) throw new TypeError(\"Unknown native operation\");",
  "      const source = record(inputs, operation.inputs.map(input => input.id));",
  "      const converted = Object.fromEntries(operation.inputs.map(input =>",
  "        [input.id, convertNativeValue(input.type, source[input.id], true).value]));",
  "      const returned = await admitted[operationId]!.call(adapter.actions, converted, context);",
  "      if (returned !== undefined) throw new TypeError(\"Native operations must return undefined\");",
  "    },",
  "    async observe(context) {",
  "      const source = record(await observe(context), manifest.observations.map(item => item.id));",
  "      return Object.fromEntries(manifest.observations.map(item =>",
  "        [item.id, convertNativeValue(item.type, source[item.id], false).value]));",
  "    },",
  "  };",
  "}"
]

end Shell.ModelInterface.Emit.SuiteNativeRuntime
