import Shell.ModelInterface.Emit.TypeScriptAsync
import Shell.ModelInterface.Emit.SuiteNativeRuntime
import Core.ModelInterface.Sha256

/-! Deterministic suite companions compose the unchanged async target. Bundle
ownership is a separate schema; payload hashing never hashes the manifest itself. -/
namespace Shell.ModelInterface.Emit.SuiteBundle

open Core.ModelInterface
open Shell.ModelInterface.Emit.TypeScript

def manifestPath : String := ".suite-bundle-generated.json"
def schema : String := "mirrors.suite-bundle/v1"
def nativeRepresentation : String := "mirrors.node-native/v1"

private partial def nativeType (type : ModelType) : EmitResult String := do
  match type with
  | .int => pure "bigint"
  | .bool => pure "boolean"
  | .str => pure "string"
  | .null => pure "null"
  | .set element => pure s!"ReadonlySet<{← nativeType element}>"
  | .seq element => pure s!"readonly ({← nativeType element})[]"
  | .tuple elements => pure ("readonly [" ++ String.intercalate ", " (← elements.mapM nativeType) ++ "]")
  | .record fields =>
      let fields ← (Shared.sortByKey (·.wireName) fields).mapM fun field => do
        pure s!"readonly {Shared.quote field.wireName}: {← nativeType field.type};"
      pure ("{ " ++ String.intercalate " " fields ++ " }")
  | .map .str value => pure s!"ReadonlyMap<string, {← nativeType value}>"
  | .variant cases =>
      let cases ← (Shared.sortByKey (·.tag) cases).mapM fun item => do
        pure ("{ readonly tag: " ++ Shared.quote item.tag ++ "; readonly value: " ++
          (← nativeType item.payload) ++ " }")
      pure (String.intercalate " | " cases)
  | _ => .error [{ code := "MIC-E-TYPE-001", message := "suite bundles require the portable Node-native subset" }]

private def renderAdapter (lock : LockedModelInterface) : EmitResult String := do
  let actions ← (Shared.sortByKey (·.id) (lock.initializers ++ lock.actions)).mapM fun action => do
    let fields ← (Shared.sortByKey (·.id) action.inputs).mapM fun input => do
      pure s!"readonly {Shared.quote input.id}: {← nativeType input.projection.type};"
    pure ("    readonly " ++ Shared.quote action.id ++ ": (inputs: { " ++
      String.intercalate " " fields ++ " }, context: ReplayContext) => void | Promise<void>;")
  let observations ← (Shared.sortByKey (·.id) lock.observations).mapM fun observation => do
    pure s!"  readonly {Shared.quote observation.id}: {← nativeType observation.type};"
  pure <| Shared.joinLines <|
    [s!"export interface {lock.modelModule}NativeObservation " ++ "{"] ++ observations ++
    ["}", "", s!"export interface {lock.modelModule}NativeAdapter " ++ "{", "  readonly actions: {"] ++ actions ++
    ["  };", s!"  observe(context: ReplayContext): {lock.modelModule}NativeObservation | Promise<{lock.modelModule}NativeObservation>;",
     "  dispose?(): void | Promise<void>;", "}"]

private def sourceProvenance (lock : LockedModelInterface) : Lean.Json := Lean.Json.mkObj [
    ("modelSha256", .str ((lock.provenance.sources.find? (·.moduleName == lock.modelModule))
      |>.map (·.contentSha256) |>.getD "")),
    ("sources", .arr ((Shared.sortByKey (·.moduleName) lock.provenance.sources).map fun source =>
      Lean.Json.mkObj [("module", .str source.moduleName), ("sha256", .str source.contentSha256)]).toArray)
  ]

private def renderCompanion (lock : LockedModelInterface) : EmitResult String := do
  let model := lock.modelModule
  let adapter ← renderAdapter lock
  let descriptor := Codec.ModelInterfaceJson.canonicalString
    (Codec.ModelInterfaceJson.encodeSemanticDescriptor lock.semanticDescriptor)
  pure <| Shared.finalLf <| String.intercalate "\n\n" [
    "// @generated by Mirrors model_interface_gen; DO NOT EDIT",
    "import type { ApalacheConfig, ModelType, NativeSuiteAdapter, ReplayContext, SuiteModel, SuitePublicManifest, SuitePublicPort } from \"mirrorecma\";",
    s!"import " ++ "{ " ++ s!"{model}ModelInterface, {model}PublicManifest, bind{model}AsyncPublicPort" ++
      " } from " ++ Shared.quote ("./" ++ model ++ "Mirror.generated.js") ++ ";",
    adapter,
    SuiteNativeRuntime.source,
    s!"export const {model}Descriptor = frozen({descriptor} as const);",
    s!"export const {model}Model: SuiteModel<{model}NativeAdapter> = frozen(" ++ "{\n" ++
    "  schema: \"mirrors.suite-model/v1\",\n" ++
    "  nativeRepresentation: \"mirrors.node-native/v1\",\n" ++
    s!"  semanticDigest: {Shared.quote lock.semanticDigest},\n" ++
    s!"  provenance: {Codec.ModelInterfaceJson.canonicalString (sourceProvenance lock)},\n" ++
    "  targetProfile: \"mirrorecma-async-v1\",\n" ++
    "  stateComputerContractVersion: \"mirrors.async-state-computer/v1\",\n" ++
    s!"  descriptor: {model}Descriptor,\n  metadata: {model}ModelInterface,\n" ++
    s!"  publicManifest: {model}PublicManifest,\n" ++
    s!"  bindPublicPort: bind{model}AsyncPublicPort,\n" ++
    s!"  bindLocal(port: {model}NativeAdapter, config: ApalacheConfig) " ++ "{\n" ++
    s!"    return bind{model}AsyncPublicPort(nativePublicPort(port, {model}PublicManifest), config);\n" ++
    "  },\n} as const);"
  ]

/-- Emit unchanged async payload plus an inert trusted model handle, canonical
private descriptor and public manifest, and independently versioned ownership. -/
def emit (lock : LockedModelInterface) : EmitResult GeneratedTree := do
  if !(lock.provenance.sources.any (·.moduleName == lock.modelModule)) then
    throw [{ code := "MIC-E-PROVENANCE-001", message := "suite bundle requires root model source provenance" }]
  let asyncTree ← TypeScriptAsync.emitTypeScriptAsync lock
  let companion ← renderCompanion lock
  let metadata := Lean.Json.mkObj [
    ("schema", .str "mirrors.suite-bundle-metadata/v1"),
    ("compilerVersion", .str lock.provenance.compilerVersion),
    ("provenanceDigest", .str lock.provenanceDigest),
    ("provenance", sourceProvenance lock),
    ("semanticDigest", .str lock.semanticDigest),
    ("nativeRepresentation", .str nativeRepresentation),
    ("targetProfile", .str TypeScriptAsync.targetProfile),
    ("stateComputerContractVersion", .str TypeScriptAsync.stateComputerContractVersion)
  ]
  let metadataBytes := Codec.ModelInterfaceJson.canonicalFileBytes metadata
  let files := Shared.sortByKey (fun file : GeneratedFile => file.relativePath) <| asyncTree.files ++ [
    { relativePath := lock.modelModule ++ ".suite.ts", bytes := companion.toUTF8 },
    { relativePath := "descriptor.json", bytes := Codec.ModelInterfaceJson.canonicalFileBytes
        (Codec.ModelInterfaceJson.encodeSemanticDescriptor lock.semanticDescriptor) },
    { relativePath := "public-manifest.json", bytes := (Shared.finalLf
        (TypeScriptAsync.renderPublicManifest lock)).toUTF8 },
    { relativePath := "bundle-metadata.json", bytes := metadataBytes }
  ]
  let hashes := files.map fun file => Lean.Json.mkObj [
    ("path", .str file.relativePath), ("sha256", .str (Sha256.digestHex file.bytes))]
  let manifest := Lean.Json.mkObj [
    ("schema", .str schema), ("profileVersion", .num 1),
    ("targetProfile", .str TypeScriptAsync.targetProfile),
    ("semanticDigest", .str lock.semanticDigest),
    ("nativeRepresentation", .str nativeRepresentation),
    ("metadataSha256", .str (Sha256.digestHex metadataBytes)),
    ("files", .arr ((Shared.sortStrings (manifestPath :: files.map (·.relativePath))).map Lean.Json.str).toArray),
    ("payloadSha256", .arr hashes.toArray)
  ]
  let allFiles := files ++ [{ relativePath := manifestPath, bytes := Codec.ModelInterfaceJson.canonicalFileBytes manifest }]
  pure { files := Shared.sortByKey (fun file : GeneratedFile => file.relativePath) allFiles }

end Shell.ModelInterface.Emit.SuiteBundle
