NL = chr(10)
head = open('.erpc.headf.lean').read()
helpers = open('.erpc.helpersf.lean').read()
reqhdr = open('.erpc.reqhdr.lean').read()
finalarms = open('.erpc.finalarms.lean').read()
resp = open('.erpc.resp3.lean').read()
out = NL.join([head.rstrip(), '', '/-! ## §6.6-style round-trips -/', '', helpers.rstrip(), reqhdr, finalarms.rstrip(), '', resp.rstrip(), ''])
open('Codec/ExplorerRpc.lean','w').write(out + NL)
print('assembled', len(out.splitlines()))
