// @generated by Mirrors model_interface_gen
// target-profile: mirrorecma-async-v1
// profile-version: 1
// semantic-sha256: d54bd0b831cdfffd1b42ec41e0cd9c71e4ad9374dce7719932a67120faeff3da
// DO NOT EDIT

import type { ApalacheConfig, AsyncStateComputer, ReplayContext, State, Value } from "mirrorecma";

export type MirrorSet<T> = readonly T[];
export type MirrorMap<K, V> = readonly (readonly [K, V])[];

type TypeShape =
  | { readonly kind: "int" | "bool" | "str" | "null" }
  | { readonly kind: "set" | "seq"; readonly element: TypeShape }
  | { readonly kind: "tuple"; readonly elements: readonly TypeShape[] }
  | { readonly kind: "record"; readonly fields: readonly (readonly [string, TypeShape])[] }
  | { readonly kind: "map"; readonly key: TypeShape; readonly value: TypeShape }
  | { readonly kind: "variant"; readonly cases: readonly (readonly [string, TypeShape])[] };

type RuntimePathSegment =
  | { readonly kind: "field"; readonly name: string }
  | { readonly kind: "index"; readonly index: number }
  | { readonly kind: "variantValue"; readonly tag: string };

function ownRecord(value: unknown): Record<string, unknown> | null {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return null;
  return value as Record<string, unknown>;
}

function exactKeys(value: Record<string, unknown>, expected: readonly string[], path: string): void {
  const actual = Object.keys(value).sort();
  const wanted = [...expected].sort();
  if (actual.length !== wanted.length || actual.some((key, i) => key !== wanted[i])) {
    throw new Error(path + ": expected keys [" + wanted.join(", ") + "], got [" + actual.join(", ") + "]");
  }
}

function comparableInitialState(root: State): State {
  const filtered = Object.create(null) as State;
  for (const [name, value] of Object.entries(root)) {
    if (!name.startsWith("#") && name !== "action_taken" && name !== "parameters") {
      filtered[name] = value;
    }
  }
  return filtered;
}

function valueIdentity(value: Value): string {
  switch (value.tag) {
    case "int": return "int:" + value.val.toString();
    case "bool": return value.val ? "bool:1" : "bool:0";
    case "str": return "str:" + JSON.stringify(value.val);
    case "null": return "null";
    case "set": return "set:[" + value.val.map(valueIdentity).sort().join(",") + "]";
    case "seq": return "seq:[" + value.val.map(valueIdentity).join(",") + "]";
    case "tuple": return "tuple:[" + value.val.map(valueIdentity).join(",") + "]";
    case "record": return "record:{" + Object.keys(value.val).sort()
      .map((key) => JSON.stringify(key) + ":" + valueIdentity(value.val[key]!)).join(",") + "}";
    case "map": return "map:[" + value.val.map(([key, item]) =>
      valueIdentity(key) + "=>" + valueIdentity(item)).sort().join(",") + "]";
    case "variant": return "variant:" + JSON.stringify(value.variantTag) + "=" + valueIdentity(value.value);
    case "unserializable": return "unserializable:" + JSON.stringify(value.val);
  }
}

function assertUniqueValues(values: readonly Value[], path: string): void {
  const seen = new Set<string>();
  for (const value of values) {
    const identity = valueIdentity(value);
    if (seen.has(identity)) throw new Error(path + ": duplicate set element or map key");
    seen.add(identity);
  }
}

function readPath(root: State, path: readonly RuntimePathSegment[], label: string): Value {
  let value: Value = { tag: "record", val: root };
  for (const segment of path) {
    if (segment.kind === "field") {
      if (value.tag !== "record" || !Object.prototype.hasOwnProperty.call(value.val, segment.name)) {
        throw new Error(label + ": missing record field " + segment.name);
      }
      value = value.val[segment.name]!;
    } else if (segment.kind === "index") {
      if ((value.tag !== "seq" && value.tag !== "tuple") || segment.index >= value.val.length) {
        throw new Error(label + ": missing index " + segment.index);
      }
      value = value.val[segment.index]!;
    } else {
      if (value.tag !== "variant" || value.variantTag !== segment.tag) {
        throw new Error(label + ": expected variant " + segment.tag);
      }
      value = value.value;
    }
  }
  return value;
}

function decodeNative(value: Value, shape: TypeShape, path: string): unknown {
  switch (shape.kind) {
    case "int": if (value.tag === "int") return value.val; break;
    case "bool": if (value.tag === "bool") return value.val; break;
    case "str": if (value.tag === "str") return value.val; break;
    case "null": if (value.tag === "null") return null; break;
    case "set":
      if (value.tag === "set") {
        assertUniqueValues(value.val, path);
        return value.val.map((item, i) => decodeNative(item, shape.element, path + "[" + i + "]"));
      }
      break;
    case "seq":
      if (value.tag === "seq") return value.val.map((item, i) => decodeNative(item, shape.element, path + "[" + i + "]"));
      break;
    case "tuple":
      if (value.tag === "tuple" && value.val.length === shape.elements.length) {
        return value.val.map((item, i) => decodeNative(item, shape.elements[i]!, path + "[" + i + "]"));
      }
      break;
    case "record":
      if (value.tag === "record") {
        exactKeys(value.val, shape.fields.map(([name]) => name), path);
        const out = Object.create(null) as Record<string, unknown>;
        for (const [name, fieldShape] of shape.fields) {
          out[name] = decodeNative(value.val[name]!, fieldShape, path + "." + name);
        }
        return out;
      }
      break;
    case "map":
      if (value.tag === "map") {
        assertUniqueValues(value.val.map(([key]) => key), path);
        return value.val.map(([key, item], i) => [
          decodeNative(key, shape.key, path + "[" + i + "].key"),
          decodeNative(item, shape.value, path + "[" + i + "].value"),
        ] as const);
      }
      break;
    case "variant":
      if (value.tag === "variant") {
        const found = shape.cases.find(([tag]) => tag === value.variantTag);
        if (found) return {
          tag: value.variantTag,
          value: decodeNative(value.value, found[1], path + ".value"),
        };
      }
      break;
  }
  throw new Error(path + ": value does not match " + shape.kind);
}

function encodeNative(value: unknown, shape: TypeShape, path: string): Value {
  switch (shape.kind) {
    case "int": if (typeof value === "bigint") return { tag: "int", val: value }; break;
    case "bool": if (typeof value === "boolean") return { tag: "bool", val: value }; break;
    case "str": if (typeof value === "string") return { tag: "str", val: value }; break;
    case "null": if (value === null) return { tag: "null" }; break;
    case "set":
    case "seq":
      if (Array.isArray(value)) {
        const val = value.map((item, i) => encodeNative(item, shape.element, path + "[" + i + "]"));
        if (shape.kind === "set") assertUniqueValues(val, path);
        return shape.kind === "set" ? { tag: "set", val } : { tag: "seq", val };
      }
      break;
    case "tuple":
      if (Array.isArray(value) && value.length === shape.elements.length) {
        return {
          tag: "tuple",
          val: value.map((item, i) => encodeNative(item, shape.elements[i]!, path + "[" + i + "]")),
        };
      }
      break;
    case "record": {
      const record = ownRecord(value);
      if (record) {
        exactKeys(record, shape.fields.map(([name]) => name), path);
        const val = Object.create(null) as Record<string, Value>;
        for (const [name, fieldShape] of shape.fields) {
          val[name] = encodeNative(record[name], fieldShape, path + "." + name);
        }
        return { tag: "record", val };
      }
      break;
    }
    case "map":
      if (Array.isArray(value)) {
        const val: [Value, Value][] = value.map((entry, i) => {
          if (!Array.isArray(entry) || entry.length !== 2) {
            throw new Error(path + "[" + i + "]: expected map entry");
          }
          return [
            encodeNative(entry[0], shape.key, path + "[" + i + "].key"),
            encodeNative(entry[1], shape.value, path + "[" + i + "].value"),
          ];
        });
        assertUniqueValues(val.map(([key]) => key), path);
        return { tag: "map", val };
      }
      break;
    case "variant": {
      const variant = ownRecord(value);
      if (variant && typeof variant.tag === "string") {
        exactKeys(variant, ["tag", "value"], path);
        const found = shape.cases.find(([tag]) => tag === variant.tag);
        if (found) return {
          tag: "variant",
          variantTag: variant.tag,
          value: encodeNative(variant.value, found[1], path + ".value"),
        };
      }
      break;
    }
  }
  throw new Error(path + ": implementation value does not match " + shape.kind);
}

export interface FinishInput {
  readonly actor: string;
}

export interface ReadInput {
  readonly actor: string;
}

export interface WriteInput {
  readonly actor: string;
}

export interface ScheduledCounterObservation {
  readonly count: bigint;
  readonly phase: MirrorMap<string, bigint>;
  readonly saved: MirrorMap<string, bigint>;
}

export interface ScheduledCounterAsyncPort {
  initialize(context: ReplayContext): Promise<void>;
  finish(input: FinishInput, context: ReplayContext): Promise<void>;
  read(input: ReadInput, context: ReplayContext): Promise<void>;
  write(input: WriteInput, context: ReplayContext): Promise<void>;
  observe(context: ReplayContext): Promise<ScheduledCounterObservation>;
}

const finish_ActorShape: TypeShape = { kind: "str" };

const read_ActorShape: TypeShape = { kind: "str" };

const write_ActorShape: TypeShape = { kind: "str" };

const scheduledCounterCountObservationShape: TypeShape = { kind: "int" };

const scheduledCounterPhaseObservationShape: TypeShape = { kind: "map", key: { kind: "str" }, value: { kind: "int" } };

const scheduledCounterSavedObservationShape: TypeShape = { kind: "map", key: { kind: "str" }, value: { kind: "int" } };

function decodeFinishInput(payload: State): FinishInput {
  return {
    actor: decodeNative(readPath(payload, [{ kind: "field", name: "parameters" }, { kind: "field", name: "actor" }], "Finish.Actor"), finish_ActorShape, "Finish.Actor") as string,
  };
}

function decodeReadInput(payload: State): ReadInput {
  return {
    actor: decodeNative(readPath(payload, [{ kind: "field", name: "parameters" }, { kind: "field", name: "actor" }], "Read.Actor"), read_ActorShape, "Read.Actor") as string,
  };
}

function decodeWriteInput(payload: State): WriteInput {
  return {
    actor: decodeNative(readPath(payload, [{ kind: "field", name: "parameters" }, { kind: "field", name: "actor" }], "Write.Actor"), write_ActorShape, "Write.Actor") as string,
  };
}

function encodeScheduledCounterObservation(observation: ScheduledCounterObservation): State {
  exactKeys(observation as unknown as Record<string, unknown>, ["count", "phase", "saved"], "ScheduledCounterObservation");
  const state = Object.create(null) as State;
  state["count"] = encodeNative(observation.count, scheduledCounterCountObservationShape, "ScheduledCounterObservation.Count");
  state["phase"] = encodeNative(observation.phase, scheduledCounterPhaseObservationShape, "ScheduledCounterObservation.Phase");
  state["saved"] = encodeNative(observation.saved, scheduledCounterSavedObservationShape, "ScheduledCounterObservation.Saved");
  return state;
}

export const ScheduledCounterSemanticDigest = "d54bd0b831cdfffd1b42ec41e0cd9c71e4ad9374dce7719932a67120faeff3da" as const;
export const ScheduledCounterAsyncTargetProfile = "mirrorecma-async-v1" as const;
export const ScheduledCounterAsyncStateComputerContractVersion = "mirrors.async-state-computer/v1" as const;
export const ScheduledCounterModelInterface = {
  semanticDigest: ScheduledCounterSemanticDigest,
  contract: {"actions":[{"id":"Finish","inputs":[{"from":{"path":[{"field":"parameters"},{"field":"actor"}],"root":"stepParameters"},"id":"Actor"}],"wireAction":"finish","wireAliases":[]},{"id":"Read","inputs":[{"from":{"path":[{"field":"parameters"},{"field":"actor"}],"root":"stepParameters"},"id":"Actor"}],"wireAction":"read","wireAliases":[]},{"id":"Write","inputs":[{"from":{"path":[{"field":"parameters"},{"field":"actor"}],"root":"stepParameters"},"id":"Actor"}],"wireAction":"write","wireAliases":[]}],"initializers":[{"id":"Initialize","inputs":[],"wireAction":"init","wireAliases":[]}],"interfaceVersion":"1.0.0","model":{"module":"ScheduledCounter","source":"test/fixtures/deterministic-scheduling/ScheduledCounter.tla"},"observations":[{"id":"Count","provenance":"implementation","wireName":"count"},{"id":"Phase","provenance":"implementation","wireName":"phase"},{"id":"Saved","provenance":"implementation","wireName":"saved"}],"schema":"mirrors.model-interface/v1","wire":{"actionVariable":"action_taken","parameterVariable":"parameters"}},
} as const;
export const ScheduledCounterPublicManifest = {"actions":[{"id":"Finish","inputs":[{"id":"Actor","type":{"kind":"str"}}]},{"id":"Read","inputs":[{"id":"Actor","type":{"kind":"str"}}]},{"id":"Write","inputs":[{"id":"Actor","type":{"kind":"str"}}]}],"initializers":[{"id":"Initialize","inputs":[]}],"interfaceDigest":"d54bd0b831cdfffd1b42ec41e0cd9c71e4ad9374dce7719932a67120faeff3da","observations":[{"id":"Count","type":{"kind":"int"}},{"id":"Phase","type":{"key":{"kind":"str"},"kind":"map","value":{"kind":"int"}}},{"id":"Saved","type":{"key":{"kind":"str"},"kind":"map","value":{"kind":"int"}}}],"schema":"mirrorgate.port/v1"} as const;

export type ScheduledCounterBindingErrorCode =
  | "configuration_mismatch"
  | "unknown_action"
  | "transition_before_initialization"
  | "input_shape_mismatch"
  | "adapter_failure"
  | "observation_shape_mismatch"
  | "context_mismatch"
  | "operation_cancelled"
  | "deadline_exceeded"
  | "reentrant_call"
  | "binding_poisoned";

export class ScheduledCounterBindingError extends Error {
  constructor(readonly code: ScheduledCounterBindingErrorCode, message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = "ScheduledCounterBindingError";
  }
}

function bindingError(code: ScheduledCounterBindingErrorCode, message: string, cause?: unknown): ScheduledCounterBindingError {
  return new ScheduledCounterBindingError(code, message, cause === undefined ? undefined : { cause });
}

function contextError(context: ReplayContext): ScheduledCounterBindingError | undefined {
  if (typeof context.deadline !== "number" || !Number.isFinite(context.deadline)) {
    return bindingError("context_mismatch", "replay deadline must be a finite monotonic instant");
  }
  if (context.signal.aborted) {
    return bindingError("operation_cancelled", "replay operation was cancelled", context.signal.reason);
  }
  if (performance.now() >= context.deadline) {
    return bindingError("deadline_exceeded", "replay deadline expired");
  }
  return undefined;
}

function ensureContextActive(context: ReplayContext): void {
  const error = contextError(context);
  if (error !== undefined) throw error;
}

function awaitPortOperation<T>(operation: PromiseLike<T>, context: ReplayContext): Promise<T> {
  const before = contextError(context);
  if (before !== undefined) {
    void Promise.resolve(operation).catch(() => undefined);
    return Promise.reject(before);
  }
  return new Promise<T>((resolve, reject) => {
    let settled = false;
    let deadlineTimer: ReturnType<typeof setTimeout> | undefined;
    const finish = (callback: () => void): void => {
      if (settled) return;
      settled = true;
      context.signal.removeEventListener("abort", onAbort);
      if (deadlineTimer !== undefined) clearTimeout(deadlineTimer);
      callback();
    };
    const onAbort = (): void => finish(() => reject(
      bindingError("operation_cancelled", "replay operation was cancelled", context.signal.reason),
    ));
    context.signal.addEventListener("abort", onAbort, { once: true });
    const armDeadline = (): void => {
      const remaining = context.deadline - performance.now();
      if (remaining <= 0) {
        finish(() => reject(bindingError("deadline_exceeded", "replay deadline expired")));
      } else {
        deadlineTimer = setTimeout(armDeadline, Math.min(Math.max(1, Math.ceil(remaining)), 2_147_483_647));
      }
    };
    armDeadline();
    void Promise.resolve(operation).then(
      (value) => finish(() => {
        const after = contextError(context);
        if (after === undefined) resolve(value); else reject(after);
      }),
      (error: unknown) => finish(() => reject(error)),
    );
  });
}

type ScheduledCounterActionId = "Finish" | "Initialize" | "Read" | "Write";

export function assertScheduledCounterCompatibleConfig(
  config: Pick<ApalacheConfig, "paramVars">,
): void {
  const expectedParamVar = "parameters";
  const actualParamVar = config.paramVars ?? "";
  if (actualParamVar !== expectedParamVar) {
    throw bindingError(
      "configuration_mismatch",
      "expected paramVars=" + expectedParamVar + ", got " + actualParamVar,
    );
  }
}

export interface ScheduledCounterAsyncBinding {
  readonly computer: AsyncStateComputer;
  assertCompatibleConfig(config: Pick<ApalacheConfig, "paramVars">): void;
  coverage(): Readonly<Record<ScheduledCounterActionId, number>>;
  assertAllActionsCovered(): void;
}

export function bindScheduledCounterAsync(
  port: ScheduledCounterAsyncPort,
  config: Pick<ApalacheConfig, "paramVars">,
): ScheduledCounterAsyncBinding {
  assertScheduledCounterCompatibleConfig(config);

  let lifecycle: "fresh" | "initialized" | "poisoned" = "fresh";
  let busy = false;
  const counts: Record<ScheduledCounterActionId, number> = {
    "Finish": 0,
    "Initialize": 0,
    "Read": 0,
    "Write": 0,
  };
  const ensureBindingActive = (): void => {
    if (lifecycle === "poisoned") {
      throw bindingError("binding_poisoned", "binding is poisoned");
    }
  };

  const computer: AsyncStateComputer = async ({ action, payload, previous: _previous }, context) => {
    ensureBindingActive();
    if (busy) {
      lifecycle = "poisoned";
      throw bindingError("reentrant_call", "binding permits one callback at a time");
    }
    busy = true;
    let actionId: ScheduledCounterActionId;
    let stage: "dispatch" | "input" | "adapter" | "observation" = "dispatch";
    try {
      ensureContextActive(context);
      switch (action) {
      case "finish":
      {
        if (lifecycle === "fresh") throw bindingError("transition_before_initialization", "transition before initialization");
        stage = "input";
        const input = decodeFinishInput(payload);
        stage = "adapter";
        ensureContextActive(context);
        await awaitPortOperation(port.finish(input, context), context);
        ensureContextActive(context);
        ensureBindingActive();
        lifecycle = "initialized";
        actionId = "Finish";
        break;
      }
      case "init":
      {
        stage = "adapter";
        ensureContextActive(context);
        await awaitPortOperation(port.initialize(context), context);
        ensureContextActive(context);
        ensureBindingActive();
        lifecycle = "initialized";
        actionId = "Initialize";
        break;
      }
      case "read":
      {
        if (lifecycle === "fresh") throw bindingError("transition_before_initialization", "transition before initialization");
        stage = "input";
        const input = decodeReadInput(payload);
        stage = "adapter";
        ensureContextActive(context);
        await awaitPortOperation(port.read(input, context), context);
        ensureContextActive(context);
        ensureBindingActive();
        lifecycle = "initialized";
        actionId = "Read";
        break;
      }
      case "write":
      {
        if (lifecycle === "fresh") throw bindingError("transition_before_initialization", "transition before initialization");
        stage = "input";
        const input = decodeWriteInput(payload);
        stage = "adapter";
        ensureContextActive(context);
        await awaitPortOperation(port.write(input, context), context);
        ensureContextActive(context);
        ensureBindingActive();
        lifecycle = "initialized";
        actionId = "Write";
        break;
      }
        default: throw bindingError("unknown_action", "unknown action " + action);
      }
      stage = "observation";
      ensureContextActive(context);
      const observation = await awaitPortOperation(port.observe(context), context);
      ensureContextActive(context);
      ensureBindingActive();
      const state = encodeScheduledCounterObservation(observation);
      ensureContextActive(context);
      ensureBindingActive();
      counts[actionId] += 1;
      return state;
    } catch (error) {
      lifecycle = "poisoned";
      if (error instanceof ScheduledCounterBindingError) throw error;
      const code = stage === "input"
        ? "input_shape_mismatch"
        : stage === "observation"
          ? "observation_shape_mismatch"
          : "adapter_failure";
      throw bindingError(code, "binding failed for action " + action, error);
    } finally {
      busy = false;
    }
  };

  return {
    computer,
    assertCompatibleConfig: assertScheduledCounterCompatibleConfig,
    coverage: () => Object.freeze({ ...counts }),
    assertAllActionsCovered: () => {
      const unseen = (Object.keys(counts) as Array<keyof typeof counts>)
        .filter((id) => counts[id] === 0);
      if (unseen.length > 0) throw new Error("uncovered actions: " + unseen.join(", "));
    },
  };
}

export interface AsyncPublicPort {
  invoke(operationId: string, inputs: Readonly<Record<string, unknown>>, context: ReplayContext): Promise<void>;
  observe(context: ReplayContext): Promise<Readonly<Record<string, unknown>>>;
}

export function bindScheduledCounterAsyncPublicPort(
  publicPort: AsyncPublicPort,
  config: Pick<ApalacheConfig, "paramVars">,
): ScheduledCounterAsyncBinding {
  const port: ScheduledCounterAsyncPort = {
    initialize: (context) => {
      return publicPort.invoke("Initialize", Object.freeze(Object.create(null) as Record<string, unknown>), context);
    },
    finish: (input, context) => {
      const values = Object.create(null) as Record<string, unknown>;
      values["Actor"] = input.actor;
      return publicPort.invoke("Finish", Object.freeze(values), context);
    },
    read: (input, context) => {
      const values = Object.create(null) as Record<string, unknown>;
      values["Actor"] = input.actor;
      return publicPort.invoke("Read", Object.freeze(values), context);
    },
    write: (input, context) => {
      const values = Object.create(null) as Record<string, unknown>;
      values["Actor"] = input.actor;
      return publicPort.invoke("Write", Object.freeze(values), context);
    },
    observe: async (context) => {
      const values = ownRecord(await publicPort.observe(context));
      if (values === null) throw new Error("public observation must be a record");
      exactKeys(values, ["Count", "Phase", "Saved"], "ScheduledCounterPublicObservation");
      return {
        count: values["Count"] as bigint,
        phase: values["Phase"] as MirrorMap<string, bigint>,
        saved: values["Saved"] as MirrorMap<string, bigint>,
      };
    },
  };
  return bindScheduledCounterAsync(port, config);
}
