#!/bin/sh
cd /mnt/c/Users/ayden/Desktop/Workspace/MirrorsRemote/dpm-20261004/skip-hit-release/build || exit 98
exec /mnt/c/Users/ayden/Desktop/Workspace/MirrorsRemote/dpm-20261004/skip-hit-release/build/dpm_native_worker.exe
