#!/bin/sh
cd /mnt/c/Users/ayden/Desktop/Workspace/MirrorsRemote/dpm-20261004/normal-v3/build || exit 98
exec /usr/bin/python3 /tmp/admitted/terminate_peer.py /mnt/c/Users/ayden/Desktop/Workspace/MirrorsRemote/dpm-20261004/normal-v3/build/dpm_native_worker.exe /tmp/work/native/12-stable-t1-normal-v3-crash-peer/terminated.json
