-- @generated by Mirrors model_interface_gen
-- target-profile: mirrorlean-v1
-- profile-version: 1
-- semantic-sha256: 193d6cc187d05c18f02ad483a44f8ad0c1634b02083df241df08b9281b045d1c
-- DO NOT EDIT
import MirrorLean.ModelInterface
namespace CounterMirror
open MirrorLean MirrorLean.ModelInterface
set_option linter.unusedVariables false
def semanticDigest : String := "193d6cc187d05c18f02ad483a44f8ad0c1634b02083df241df08b9281b045d1c"
def metadata : GeneratedMetadata := { semanticDigest := semanticDigest, contractJson := "{\"actions\":[{\"id\":\"Tick\",\"inputs\":[{\"from\":{\"path\":[{\"field\":\"parameters\"},{\"field\":\"stride\"}],\"root\":\"stepParameters\"},\"id\":\"Stride\"}],\"wireAction\":\"tick\",\"wireAliases\":[]}],\"initializers\":[{\"id\":\"Initialize\",\"inputs\":[],\"wireAction\":\"init\",\"wireAliases\":[]}],\"interfaceVersion\":\"1.0.0\",\"model\":{\"module\":\"Counter\",\"source\":\"specs/Counter.tla\"},\"observations\":[{\"id\":\"Count\",\"provenance\":\"implementation\",\"wireName\":\"count\"}],\"schema\":\"mirrors.model-interface/v1\",\"wire\":{\"actionVariable\":\"action_taken\",\"parameterVariable\":\"parameters\"}}" }
def assertCompatibleConfig (config : ApalacheConfig) : Except BindingError Unit := do
  if config.paramVars.getD "" != "parameters" then
    throw { code := "configuration_mismatch", message := "effective paramVars mismatch" }
structure TickInput where
  «stride» : Int

structure Observation where
  «count» : Int
structure Port where
  «initialize» : IO (Except BindingError Unit)
  «tick» : TickInput → IO (Except BindingError Unit)
  observe : IO (Except BindingError Observation)
private def encodeObservation (observation : Observation) : Except BindingError State := do
  let value0 ← NativeCodec.encode observation.«count»
  pure (State.ofList [("count", value0)])

private inductive Lifecycle where
  | fresh | initialized | poisoned
  deriving BEq
private structure RuntimeState where
  lifecycle : Lifecycle := .fresh
  busy : Bool := false
  counts : Array (String × Nat)

private def poison {α : Type} (runtime : IO.Ref RuntimeState) (error : BindingError) :
    IO (Except BindingError α) := do
  runtime.modify fun state => { state with lifecycle := .poisoned, busy := false }
  pure (.error error)

structure Binding where
  computer : FallibleStateComputer
  coverage : IO (Array (String × Nat))
  assertAllActionsCovered : IO (Except BindingError Unit)

def Binding.toLocalBinding (binding : Binding)
    (dispose : IO (Except BindingError Unit) := pure (.ok ())) : LocalBinding :=
  { semanticDigest := semanticDigest, computer := binding.computer,
    assertCompatibleConfig := assertCompatibleConfig, coverage := binding.coverage, dispose }

private def compute (port : Port) (runtime : IO.Ref RuntimeState) : FallibleStateComputer :=
  fun action params _previous => do
    let acquired : Except BindingError Lifecycle ← runtime.modifyGet fun state =>
      if state.lifecycle == .poisoned then
        (.error { code := "binding_poisoned", message := "binding is poisoned" }, state)
      else if state.busy then
        (.error { code := "adapter_failure", message := "concurrent binding callback" },
          { state with lifecycle := .poisoned })
      else (.ok state.lifecycle, { state with busy := true })
    let phase ← match acquired with
      | .ok phase => pure phase
      | .error error => return .error error
    let initial := Value.record (params.toArray.filter fun (key, _) =>
      !key.startsWith "#" && key != "action_taken" && key != "parameters")
    let payload := State.toValue params
    let selected : Except BindingError (String × IO (Except BindingError Unit)) := do
      match action with

      | "init" => do
        pure ("Initialize", port.«initialize»)

      | "tick" => do
        if phase == .fresh then throw { code := "transition_before_initialization", message := "transition before initialization" }
        let input0 : Int ← (readPath payload [.field "parameters", .field "stride"]).bind NativeCodec.decode
        pure ("Tick", port.«tick» { «stride» := input0 })


      | _ => throw { code := "unknown_action", message := "unknown wire action" }
    let (stableAction, handler) ← match selected with
      | .ok selected => pure selected
      | .error error => return ← poison runtime error
    let handled ← try handler catch error =>
      pure (.error { code := "adapter_failure", message := toString error })
    match handled with
    | .error error => return ← poison runtime { error with code := "adapter_failure" }
    | .ok () => pure ()
    if (← runtime.get).lifecycle == .poisoned then
      return ← poison runtime { code := "binding_poisoned", message := "binding is poisoned" }
    let observed ← try port.observe catch error =>
      pure (.error { code := "observation_shape_mismatch", message := toString error })
    let observation ← match observed with
      | .ok observation => pure observation
      | .error error => return ← poison runtime { error with code := "observation_shape_mismatch" }
    let encoded := encodeObservation observation
    let report ← match encoded with
      | .ok report => pure report
      | .error error => return ← poison runtime { error with code := "observation_shape_mismatch" }
    let committed ← runtime.modifyGet fun state =>
      if state.lifecycle == .poisoned then (false, { state with busy := false })
      else (true, { state with
        lifecycle := .initialized, busy := false
        counts := state.counts.map fun (name, count) =>
          (name, if name == stableAction then count + 1 else count) })
    if !committed then return .error { code := "binding_poisoned", message := "binding is poisoned" }
    pure (.ok report)

def bind (port : Port) (config : ApalacheConfig) : IO (Except BindingError Binding) := do
  match assertCompatibleConfig config with
  | .error error => return .error error
  | .ok () => pure ()

  let runtime ← IO.mkRef ({ counts := #[("Initialize", 0), ("Tick", 0)] } : RuntimeState)
  pure (.ok {
    computer := compute port runtime
    coverage := return (← runtime.get).counts
    assertAllActionsCovered := do
      if (← runtime.get).counts.any (fun (_, count) => count == 0) then
        return .error { code := "uncovered_action", message := "declared actions remain uncovered" }
      pure (.ok ()) })
end CounterMirror
