// @generated by Mirrors model_interface_gen
// target-profile: mirrorrust-v1
// profile-version: 1
// semantic-sha256: 193d6cc187d05c18f02ad483a44f8ad0c1634b02083df241df08b9281b045d1c
// DO NOT EDIT
use mirrorrust::{ApalacheConfig, BindingError, FallibleStateComputer, GeneratedModelInterface, State, Value};
use num_bigint::BigInt;
use std::collections::BTreeMap;

pub trait NativeCodec: Sized {
    fn decode(value: &Value) -> Result<Self, BindingError>;
    fn encode(&self) -> Result<Value, BindingError>;
}
fn shape() -> BindingError { BindingError::new("input_shape_mismatch", "value does not match declared type") }
fn equivalent(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Set(a), Value::Set(b)) => a.len() == b.len() && a.iter().all(|x| b.iter().any(|y| equivalent(x, y))),
        (Value::Map(a), Value::Map(b)) => a.len() == b.len() && a.iter().all(|(k,v)| b.iter().any(|(l,w)| equivalent(k,l) && equivalent(v,w))),
        (Value::Seq(a), Value::Seq(b)) | (Value::Tuple(a), Value::Tuple(b)) => a.len() == b.len() && a.iter().zip(b).all(|(x,y)| equivalent(x,y)),
        (Value::Record(a), Value::Record(b)) => a.len() == b.len() && a.iter().all(|(k,v)| b.get(k).is_some_and(|w| equivalent(v,w))),
        (Value::Variant(a,v), Value::Variant(b,w)) => a == b && equivalent(v,w),
        _ => a == b,
    }
}
fn unique(values: &[Value]) -> Result<(), BindingError> {
    for (i, value) in values.iter().enumerate() {
        if values[..i].iter().any(|other| equivalent(value, other)) { return Err(shape()); }
    }
    Ok(())
}
macro_rules! scalar_codec {
    ($ty:ty, $case:ident) => {
        impl NativeCodec for $ty {
            fn decode(value: &Value) -> Result<Self, BindingError> {
                if let Value::$case(value) = value { Ok(value.clone()) } else { Err(shape()) }
            }
            fn encode(&self) -> Result<Value, BindingError> { Ok(Value::$case(self.clone())) }
        }
    };
}
scalar_codec!(BigInt, Int);
scalar_codec!(bool, Bool);
scalar_codec!(String, Str);
#[derive(Debug, Clone)]
pub struct MirrorNull;
impl NativeCodec for MirrorNull {
    fn decode(value: &Value) -> Result<Self, BindingError> { if matches!(value, Value::Null) { Ok(Self) } else { Err(shape()) } }
    fn encode(&self) -> Result<Value, BindingError> { Ok(Value::Null) }
}
#[derive(Debug, Clone)]
pub struct MirrorSeq<T>(pub Vec<T>);
#[derive(Debug, Clone)]
pub struct MirrorSet<T>(pub Vec<T>);
#[derive(Debug, Clone)]
pub struct MirrorMap<T>(pub BTreeMap<String, T>);
impl<T: NativeCodec> NativeCodec for MirrorSeq<T> {
    fn decode(value: &Value) -> Result<Self, BindingError> {
        if let Value::Seq(items) = value { Ok(Self(items.iter().map(T::decode).collect::<Result<_,_>>()?)) } else { Err(shape()) }
    }
    fn encode(&self) -> Result<Value, BindingError> { Ok(Value::Seq(self.0.iter().map(T::encode).collect::<Result<_,_>>()?)) }
}
impl<T: NativeCodec> NativeCodec for MirrorSet<T> {
    fn decode(value: &Value) -> Result<Self, BindingError> {
        if let Value::Set(items) = value {
            let decoded = items.iter().map(T::decode).collect::<Result<Vec<_>,_>>()?;
            unique(items)?;
            Ok(Self(decoded))
        } else { Err(shape()) }
    }
    fn encode(&self) -> Result<Value, BindingError> {
        let values = self.0.iter().map(T::encode).collect::<Result<Vec<_>,_>>()?;
        unique(&values).map_err(|e| BindingError::new("observation_shape_mismatch", e.message))?;
        Ok(Value::Set(values))
    }
}
impl<T: NativeCodec> NativeCodec for MirrorMap<T> {
    fn decode(value: &Value) -> Result<Self, BindingError> {
        if let Value::Map(items) = value {
            let mut result = BTreeMap::new();
            for (key, value) in items {
                let key = String::decode(key)?;
                if result.insert(key, T::decode(value)?).is_some() { return Err(shape()); }
            }
            Ok(Self(result))
        } else { Err(shape()) }
    }
    fn encode(&self) -> Result<Value, BindingError> {
        Ok(Value::Map(self.0.iter().map(|(k,v)| Ok((Value::Str(k.clone()), v.encode()?))).collect::<Result<_,BindingError>>()?))
    }
}
enum Segment { Field(&'static str), Index(usize), Variant(&'static str) }
fn read_path<'a>(root: &'a Value, path: &[Segment]) -> Result<&'a Value, BindingError> {
    let mut value = root;
    for segment in path {
        value = match (segment, value) {
            (Segment::Field(name), Value::Record(fields)) => fields.get(*name).ok_or_else(shape)?,
            (Segment::Index(index), Value::Seq(items) | Value::Tuple(items)) => items.get(*index).ok_or_else(shape)?,
            (Segment::Variant(tag), Value::Variant(actual, payload)) if *tag == actual => payload,
            _ => return Err(shape()),
        };
    }
    Ok(value)
}
#[derive(Clone, Copy, PartialEq)]
enum Lifecycle { Fresh, Initialized, Poisoned }

pub const SEMANTIC_DIGEST: &str = "193d6cc187d05c18f02ad483a44f8ad0c1634b02083df241df08b9281b045d1c";
pub const CONTRACT_JSON: &str = "{\"actions\":[{\"id\":\"Tick\",\"inputs\":[{\"from\":{\"path\":[{\"field\":\"parameters\"},{\"field\":\"stride\"}],\"root\":\"stepParameters\"},\"id\":\"Stride\"}],\"wireAction\":\"tick\",\"wireAliases\":[]}],\"initializers\":[{\"id\":\"Initialize\",\"inputs\":[],\"wireAction\":\"init\",\"wireAliases\":[]}],\"interfaceVersion\":\"1.0.0\",\"model\":{\"module\":\"Counter\",\"source\":\"specs/Counter.tla\"},\"observations\":[{\"id\":\"Count\",\"provenance\":\"implementation\",\"wireName\":\"count\"}],\"schema\":\"mirrors.model-interface/v1\",\"wire\":{\"actionVariable\":\"action_taken\",\"parameterVariable\":\"parameters\"}}";
pub fn model_interface() -> GeneratedModelInterface {
    GeneratedModelInterface { semantic_digest: SEMANTIC_DIGEST.into(), contract_json: CONTRACT_JSON.into() }
}
pub fn assert_compatible_config(config: &ApalacheConfig) -> Result<(), BindingError> {
    if config.param_vars.as_deref().unwrap_or("") != "parameters" {
        return Err(BindingError::new("configuration_mismatch", "effective paramVars mismatch"));
    }
    Ok(())
}
#[derive(Debug, Clone)]
pub struct TickInput {
    pub stride: BigInt,
}

#[derive(Debug, Clone)]
pub struct CounterObservation {
    pub count: BigInt,
}
pub trait CounterPort {
    fn initialize(&mut self) -> Result<(), BindingError>;
    fn tick(&mut self, input: TickInput) -> Result<(), BindingError>;
    fn observe(&mut self) -> Result<CounterObservation, BindingError>;
}
pub struct CounterBinding<P: CounterPort> {
    port: P,
    lifecycle: Lifecycle,
    counts: BTreeMap<&'static str, usize>,
}
pub fn bind_counter<P: CounterPort>(port: P, config: &ApalacheConfig) -> Result<CounterBinding<P>, BindingError> {
    assert_compatible_config(config)?;
    Ok(CounterBinding { port, lifecycle: Lifecycle::Fresh, counts: BTreeMap::from([("Initialize", 0), ("Tick", 0)]) })
}
impl<P: CounterPort> CounterBinding<P> {
    pub fn into_local_binding(self) -> Result<mirrorrust::LocalBinding, BindingError> where P: 'static {
        let semantic_digest = mirrorrust::SemanticDigest::from_hex(SEMANTIC_DIGEST).map_err(|e| BindingError::new("descriptor_digest_invalid", e.to_string()))?;
        Ok(mirrorrust::LocalBinding { semantic_digest, computer: Box::new(self), assert_compatible_config: Box::new(assert_compatible_config), dispose: Box::new(|| Ok(())) })
    }
    pub fn coverage(&self) -> BTreeMap<&'static str, usize> { self.counts.clone() }
    pub fn assert_all_actions_covered(&self) -> Result<(), BindingError> {
        if self.counts.values().any(|count| *count == 0) { return Err(BindingError::new("uncovered_action", "declared actions remain uncovered")); }
        Ok(())
    }
}
impl<P: CounterPort> FallibleStateComputer for CounterBinding<P> {
    fn compute(&mut self, action: &str, params: &State, _prev: &State) -> Result<State, BindingError> {
        if self.lifecycle == Lifecycle::Poisoned { return Err(BindingError::new("binding_poisoned", "binding is poisoned")); }
        let mut stage = "input_shape_mismatch";
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            let initial = Value::Record(params.iter().filter(|(k,_)| !k.starts_with('#') && *k != "action_taken" && *k != "parameters").map(|(k,v)| (k.clone(), v.clone())).collect());
            let payload = Value::Record(params.clone());
            let stable_action = match action {
            "init" => {
                stage = "adapter_failure";
                self.port.initialize()?;
                "Initialize"
            },

            "tick" => {
                if self.lifecycle == Lifecycle::Fresh { return Err(BindingError::new("transition_before_initialization", "transition before initialization")); }
                let input = TickInput {
                    stride: read_path(&payload, &[Segment::Field("parameters"), Segment::Field("stride")]).and_then(<BigInt>::decode).map_err(|e| BindingError::new(e.code, e.message + " at " + "Tick.Stride"))?,
                };
                stage = "adapter_failure";
                self.port.tick(input)?;
                "Tick"
            },

                _ => return Err(BindingError::new("unknown_action", "unknown wire action")),
            };
            stage = "observation_shape_mismatch";
            let observation = self.port.observe()?;
            let mut state = State::new();
            state.insert("count".into(), observation.count.encode()?);
            *self.counts.get_mut(stable_action).expect("generated action") += 1;
            self.lifecycle = Lifecycle::Initialized;
            Ok(state)
        }));
        match result {
            Ok(Ok(state)) => Ok(state),
            Ok(Err(error)) => {
                self.lifecycle = Lifecycle::Poisoned;
                if stage == "input_shape_mismatch" { Err(error) } else { Err(BindingError::new(stage, error.message)) }
            },
            Err(_) => { self.lifecycle = Lifecycle::Poisoned; Err(BindingError::new(stage, "binding callback panicked")) },
        }
    }
}
