#!/bin/sh
cd /mnt/c/Users/ayden/Desktop/Workspace/MirrorsRemote/dpm-20261004/duplicate-sink-call/build || exit 98
exec /mnt/c/Users/ayden/Desktop/Workspace/MirrorsRemote/dpm-20261004/duplicate-sink-call/build/dpm_native_worker.exe
