// @generated by Mirrors model_interface_gen
// target-profile: mirrorcpp-v1
// profile-version: 1
// semantic-sha256: 193d6cc187d05c18f02ad483a44f8ad0c1634b02083df241df08b9281b045d1c
// DO NOT EDIT
#pragma once

#include <mirrorcpp/mirrorcpp.hpp>
#include <algorithm>
#include <cstddef>
#include <functional>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <utility>
#include <variant>
#include <vector>

namespace mirrors_generated::counter {

inline constexpr std::string_view CounterSemanticDigest = "193d6cc187d05c18f02ad483a44f8ad0c1634b02083df241df08b9281b045d1c";
inline const mirrorcpp::GeneratedModelInterface CounterModelInterface{
    std::string(CounterSemanticDigest),
    "{\"actions\":[{\"id\":\"Tick\",\"inputs\":[{\"from\":{\"path\":[{\"field\":\"parameters\"},{\"field\":\"stride\"}],\"root\":\"stepParameters\"},\"id\":\"Stride\"}],\"wireAction\":\"tick\",\"wireAliases\":[]}],\"initializers\":[{\"id\":\"Initialize\",\"inputs\":[],\"wireAction\":\"init\",\"wireAliases\":[]}],\"interfaceVersion\":\"1.0.0\",\"model\":{\"module\":\"Counter\",\"source\":\"specs/Counter.tla\"},\"observations\":[{\"id\":\"Count\",\"provenance\":\"implementation\",\"wireName\":\"count\"}],\"schema\":\"mirrors.model-interface/v1\",\"wire\":{\"actionVariable\":\"action_taken\",\"parameterVariable\":\"parameters\"}}",
};

enum class Lifecycle { fresh, initialized, poisoned };
enum class Stage { dispatch, input, adapter, observation };

class BindingError : public mirrorcpp::ModelInterfaceBindingError {
 public:
  BindingError(std::string code, std::string message)
      : mirrorcpp::ModelInterfaceBindingError(std::move(code), std::move(message)) {}
};

inline BindingError binding_error(std::string code, std::string message) {
  return BindingError(std::move(code), std::move(message));
}

struct PathSegment {
  enum class Kind { field, index, variant_value };
  Kind kind;
  std::string text;
  std::size_t position = 0;
  static PathSegment field(std::string value) { return {Kind::field, std::move(value), 0}; }
  static PathSegment index(std::size_t value) { return {Kind::index, {}, value}; }
  static PathSegment variant(std::string value) { return {Kind::variant_value, std::move(value), 0}; }
};

inline mirrorcpp::State comparable_initial_state(const mirrorcpp::State& root) {
  mirrorcpp::State filtered;
  for (const auto& [name, value] : root) {
    if (!name.starts_with("#") && name != "action_taken" && name != "parameters") {
      filtered.emplace(name, value);
    }
  }
  return filtered;
}

inline mirrorcpp::Value read_path(const mirrorcpp::State& root,
    const std::vector<PathSegment>& path, std::string_view label) {
  mirrorcpp::Value value(mirrorcpp::Value::Record{root});
  for (const auto& segment : path) {
    if (segment.kind == PathSegment::Kind::field) {
      if (!value.is<mirrorcpp::Value::Record>()) throw binding_error("input_shape_mismatch", std::string(label) + ": record expected");
      const auto& fields = value.get<mirrorcpp::Value::Record>().fields;
      const auto found = fields.find(segment.text);
      if (found == fields.end()) throw binding_error("input_shape_mismatch", std::string(label) + ": missing field " + segment.text);
      value = found->second;
    } else if (segment.kind == PathSegment::Kind::index) {
      const std::vector<mirrorcpp::Value>* values = nullptr;
      if (value.is<mirrorcpp::Value::Seq>()) values = &value.get<mirrorcpp::Value::Seq>().elems;
      if (value.is<mirrorcpp::Value::Tuple>()) values = &value.get<mirrorcpp::Value::Tuple>().elems;
      if (values == nullptr || segment.position >= values->size()) throw binding_error("input_shape_mismatch", std::string(label) + ": index out of range");
      value = (*values)[segment.position];
    } else {
      if (!value.is<mirrorcpp::Value::Variant>() || value.get<mirrorcpp::Value::Variant>().tag != segment.text) throw binding_error("input_shape_mismatch", std::string(label) + ": variant mismatch");
      value = *value.get<mirrorcpp::Value::Variant>().value;
    }
  }
  if (path.empty()) throw binding_error("input_shape_mismatch", std::string(label) + ": empty path cannot select the state record");
  return value;
}

struct MirrorNull {};
template <typename T> struct MirrorSet { std::vector<T> values; };
template <typename T> struct MirrorSeq { std::vector<T> values; };
template <typename... T> struct MirrorTuple { std::tuple<T...> values; };

template <std::size_t N> struct FixedString {
  char value[N];
  constexpr FixedString(const char (&source)[N]) { std::copy_n(source, N, value); }
  constexpr std::string_view view() const { return {value, N - 1}; }
};
template <FixedString Name, typename T> struct RecordField {
  using value_type = T;
  static constexpr auto name = Name;
  T value;
};
template <typename... Fields> struct MirrorRecord { std::tuple<Fields...> fields; };
template <typename T> struct MirrorMap { std::vector<std::pair<std::string, T>> entries; };
template <FixedString Name, typename T> struct VariantCase {
  using value_type = T;
  static constexpr auto name = Name;
  T value;
};
template <typename... Cases> struct MirrorVariant { std::variant<Cases...> value; };

inline std::string child_path(std::string_view path, std::string_view child) {
  return std::string(path) + "." + std::string(child);
}
inline void require_unique(const std::vector<mirrorcpp::Value>& values, std::string_view path) {
  for (std::size_t i = 0; i < values.size(); ++i) {
    for (std::size_t j = i + 1; j < values.size(); ++j) {
      if (values[i] == values[j]) throw binding_error("observation_shape_mismatch", std::string(path) + ": duplicate set element or map key");
    }
  }
}

template <typename T> struct NativeCodec;
template <typename T> T decode_native(const mirrorcpp::Value& value, std::string_view path) { return NativeCodec<T>::decode(value, path); }
template <typename T> mirrorcpp::Value encode_native(const T& value, std::string_view path) { return NativeCodec<T>::encode(value, path); }

template <> struct NativeCodec<mirrorcpp::Value::Int> {
  static mirrorcpp::Value::Int decode(const mirrorcpp::Value& value, std::string_view path) {
    if (!value.is_int()) throw binding_error("input_shape_mismatch", std::string(path) + ": integer expected");
    return value.get<mirrorcpp::Value::Int>();
  }
  static mirrorcpp::Value encode(const mirrorcpp::Value::Int& value, std::string_view) { return mirrorcpp::Value(value); }
};
template <> struct NativeCodec<bool> {
  static bool decode(const mirrorcpp::Value& value, std::string_view path) {
    if (!value.is_bool()) throw binding_error("input_shape_mismatch", std::string(path) + ": bool expected");
    return value.get<bool>();
  }
  static mirrorcpp::Value encode(bool value, std::string_view) { return mirrorcpp::Value(value); }
};
template <> struct NativeCodec<std::string> {
  static std::string decode(const mirrorcpp::Value& value, std::string_view path) {
    if (!value.is_str()) throw binding_error("input_shape_mismatch", std::string(path) + ": string expected");
    return value.get<std::string>();
  }
  static mirrorcpp::Value encode(const std::string& value, std::string_view) { return mirrorcpp::Value(value); }
};
template <> struct NativeCodec<MirrorNull> {
  static MirrorNull decode(const mirrorcpp::Value& value, std::string_view path) {
    if (!value.is_null()) throw binding_error("input_shape_mismatch", std::string(path) + ": null expected");
    return {};
  }
  static mirrorcpp::Value encode(MirrorNull, std::string_view) { return mirrorcpp::Value(nullptr); }
};
template <typename T> struct NativeCodec<MirrorSet<T>> {
  static MirrorSet<T> decode(const mirrorcpp::Value& value, std::string_view path) {
    if (!value.is<mirrorcpp::Value::Set>()) throw binding_error("input_shape_mismatch", std::string(path) + ": set expected");
    const auto& source = value.get<mirrorcpp::Value::Set>().elems;
    for (std::size_t i = 0; i < source.size(); ++i) for (std::size_t j = i + 1; j < source.size(); ++j) if (source[i] == source[j]) throw binding_error("input_shape_mismatch", std::string(path) + ": duplicate set element");
    MirrorSet<T> result;
    for (std::size_t i = 0; i < source.size(); ++i) result.values.push_back(decode_native<T>(source[i], std::string(path) + "[" + std::to_string(i) + "]"));
    return result;
  }
  static mirrorcpp::Value encode(const MirrorSet<T>& value, std::string_view path) {
    std::vector<mirrorcpp::Value> encoded;
    for (std::size_t i = 0; i < value.values.size(); ++i) encoded.push_back(encode_native<T>(value.values[i], std::string(path) + "[" + std::to_string(i) + "]"));
    require_unique(encoded, path);
    return mirrorcpp::Value(mirrorcpp::Value::Set{std::move(encoded)});
  }
};
template <typename T> struct NativeCodec<MirrorSeq<T>> {
  static MirrorSeq<T> decode(const mirrorcpp::Value& value, std::string_view path) {
    if (!value.is<mirrorcpp::Value::Seq>()) throw binding_error("input_shape_mismatch", std::string(path) + ": sequence expected");
    MirrorSeq<T> result; const auto& source = value.get<mirrorcpp::Value::Seq>().elems;
    for (std::size_t i = 0; i < source.size(); ++i) result.values.push_back(decode_native<T>(source[i], std::string(path) + "[" + std::to_string(i) + "]"));
    return result;
  }
  static mirrorcpp::Value encode(const MirrorSeq<T>& value, std::string_view path) {
    std::vector<mirrorcpp::Value> encoded; for (std::size_t i = 0; i < value.values.size(); ++i) encoded.push_back(encode_native<T>(value.values[i], std::string(path) + "[" + std::to_string(i) + "]"));
    return mirrorcpp::Value(mirrorcpp::Value::Seq{std::move(encoded)});
  }
};
template <typename... T> struct NativeCodec<MirrorTuple<T...>> {
  template <std::size_t... I> static MirrorTuple<T...> decode_items(const std::vector<mirrorcpp::Value>& source, std::string_view path, std::index_sequence<I...>) {
    return {std::tuple<T...>{decode_native<T>(source[I], std::string(path) + "[" + std::to_string(I) + "]")...}};
  }
  static MirrorTuple<T...> decode(const mirrorcpp::Value& value, std::string_view path) {
    if (!value.is<mirrorcpp::Value::Tuple>() || value.get<mirrorcpp::Value::Tuple>().elems.size() != sizeof...(T)) throw binding_error("input_shape_mismatch", std::string(path) + ": tuple shape mismatch");
    return decode_items(value.get<mirrorcpp::Value::Tuple>().elems, path, std::index_sequence_for<T...>{});
  }
  template <std::size_t... I> static mirrorcpp::Value encode_items(const MirrorTuple<T...>& value, std::string_view path, std::index_sequence<I...>) {
    std::vector<mirrorcpp::Value> encoded{encode_native<std::tuple_element_t<I, std::tuple<T...>>>(std::get<I>(value.values), std::string(path) + "[" + std::to_string(I) + "]")...};
    return mirrorcpp::Value(mirrorcpp::Value::Tuple{std::move(encoded)});
  }
  static mirrorcpp::Value encode(const MirrorTuple<T...>& value, std::string_view path) { return encode_items(value, path, std::index_sequence_for<T...>{}); }
};
template <typename Field> void encode_record_field(mirrorcpp::Value::Record& target, const Field& field, std::string_view path) {
  target.fields.emplace(std::string(Field::name.view()), encode_native<typename Field::value_type>(field.value, child_path(path, Field::name.view())));
}
template <typename... Fields> struct NativeCodec<MirrorRecord<Fields...>> {
  static MirrorRecord<Fields...> decode(const mirrorcpp::Value& value, std::string_view path) {
    if (!value.is<mirrorcpp::Value::Record>()) throw binding_error("input_shape_mismatch", std::string(path) + ": record expected");
    const auto& source = value.get<mirrorcpp::Value::Record>().fields;
    if (source.size() != sizeof...(Fields) || (!(source.contains(std::string(Fields::name.view()))) || ...)) throw binding_error("input_shape_mismatch", std::string(path) + ": record fields mismatch");
    return {std::tuple<Fields...>{Fields{decode_native<typename Fields::value_type>(source.at(std::string(Fields::name.view())), child_path(path, Fields::name.view()))}...}};
  }
  static mirrorcpp::Value encode(const MirrorRecord<Fields...>& value, std::string_view path) {
    mirrorcpp::Value::Record result; std::apply([&](const auto&... field) { (encode_record_field(result, field, path), ...); }, value.fields); return mirrorcpp::Value(std::move(result));
  }
};
template <typename T> struct NativeCodec<MirrorMap<T>> {
  static MirrorMap<T> decode(const mirrorcpp::Value& value, std::string_view path) {
    if (!value.is<mirrorcpp::Value::Map>()) throw binding_error("input_shape_mismatch", std::string(path) + ": map expected");
    MirrorMap<T> result; std::set<std::string> keys; const auto& source = value.get<mirrorcpp::Value::Map>().entries;
    for (std::size_t i = 0; i < source.size(); ++i) { if (!source[i].first.is_str()) throw binding_error("input_shape_mismatch", std::string(path) + ": string map key expected"); const auto key = source[i].first.get<std::string>(); if (!keys.insert(key).second) throw binding_error("input_shape_mismatch", std::string(path) + ": duplicate map key"); result.entries.emplace_back(key, decode_native<T>(source[i].second, child_path(path, key))); } return result;
  }
  static mirrorcpp::Value encode(const MirrorMap<T>& value, std::string_view path) {
    mirrorcpp::Value::Map result; std::set<std::string> keys; for (const auto& [key, item] : value.entries) { if (!keys.insert(key).second) throw binding_error("observation_shape_mismatch", std::string(path) + ": duplicate map key"); result.entries.emplace_back(mirrorcpp::Value(key), encode_native<T>(item, child_path(path, key))); } return mirrorcpp::Value(std::move(result));
  }
};
template <typename... Cases> struct NativeCodec<MirrorVariant<Cases...>> {
  static MirrorVariant<Cases...> decode(const mirrorcpp::Value& value, std::string_view path) {
    if (!value.is<mirrorcpp::Value::Variant>()) throw binding_error("input_shape_mismatch", std::string(path) + ": variant expected");
    const auto& source = value.get<mirrorcpp::Value::Variant>(); std::optional<MirrorVariant<Cases...>> result;
    ([&] { if (source.tag == Cases::name.view()) result = MirrorVariant<Cases...>{Cases{decode_native<typename Cases::value_type>(*source.value, child_path(path, source.tag))}}; }(), ...);
    if (!result) throw binding_error("input_shape_mismatch", std::string(path) + ": unknown variant tag");
    return std::move(*result);
  }
  static mirrorcpp::Value encode(const MirrorVariant<Cases...>& value, std::string_view path) {
    return std::visit([&](const auto& item) { using Case = std::decay_t<decltype(item)>; return mirrorcpp::Value(mirrorcpp::Value::Variant{std::string(Case::name.view()), mirrorcpp::Box<mirrorcpp::Value>(encode_native<typename Case::value_type>(item.value, child_path(path, Case::name.view())))}); }, value.value);
  }
};


struct TickInput {
  mirrorcpp::Value::Int stride;
};

struct CounterObservation {
  mirrorcpp::Value::Int count;
};

struct CounterPort {
  virtual ~CounterPort() = default;
  virtual void initialize() = 0;
  virtual void tick(const TickInput& input) = 0;
  virtual CounterObservation observe() = 0;
};


inline TickInput decode_tick_input(const mirrorcpp::State& payload) {
  return TickInput{
      .stride = decode_native<mirrorcpp::Value::Int>(read_path(payload, std::vector<PathSegment>{PathSegment::field("parameters"), PathSegment::field("stride")}, "Tick.Stride"), "Tick.Stride"),
  };
}

inline mirrorcpp::State encode_counter_observation(const CounterObservation& observation) {
  mirrorcpp::State state;
  state.emplace("count", encode_native<mirrorcpp::Value::Int>(observation.count, "CounterObservation.Count"));
  return state;
}

struct CounterBinding {
  mirrorcpp::StateComputer computer;
  std::function<std::map<std::string, std::size_t>()> coverage;
  std::function<void()> assert_all_actions_covered;
};

inline CounterBinding bind_counter(CounterPort& port, const mirrorcpp::ApalacheConfig& config) {
  const std::string expected_param_var = "parameters";
  if (config.param_vars != expected_param_var) throw binding_error("configuration_mismatch", "effective paramVars mismatch");
  struct Runtime {
    CounterPort* port;
    Lifecycle lifecycle = Lifecycle::fresh;
    std::map<std::string, std::size_t> counts{
        {"Initialize", 0},
        {"Tick", 0},
    };
    bool running = false;
  };
  auto runtime = std::make_shared<Runtime>();
  runtime->port = &port;
  mirrorcpp::StateComputer computer = [runtime](std::string_view wire_action, const mirrorcpp::State& payload, const mirrorcpp::State&) -> mirrorcpp::State {
    if (runtime->lifecycle == Lifecycle::poisoned) throw binding_error("binding_poisoned", "binding is poisoned");
    if (runtime->running) { runtime->lifecycle = Lifecycle::poisoned; throw binding_error("adapter_failure", "binding callbacks must not be reentrant"); }
    runtime->running = true;
    Stage stage = Stage::dispatch;
    std::string stable_action;
    try {
    if (wire_action == "init") {
      stage = Stage::adapter;
      runtime->port->initialize();
      if (runtime->lifecycle == Lifecycle::poisoned) throw binding_error("adapter_failure", "reentrant callback poisoned the binding");
      runtime->lifecycle = Lifecycle::initialized;
      stable_action = "Initialize";
    }

    else if (wire_action == "tick") {
      if (runtime->lifecycle == Lifecycle::fresh) {
        throw binding_error("transition_before_initialization", "transition before initialization");
      }
      stage = Stage::input;
      const auto input = decode_tick_input(payload);
      stage = Stage::adapter;
      runtime->port->tick(input);
      if (runtime->lifecycle == Lifecycle::poisoned) throw binding_error("adapter_failure", "reentrant callback poisoned the binding");
      runtime->lifecycle = Lifecycle::initialized;
      stable_action = "Tick";
    }

    else {
      throw binding_error("unknown_action", "unknown wire action");
    }
    stage = Stage::observation;
    const auto observation = runtime->port->observe();
    if (runtime->lifecycle == Lifecycle::poisoned) throw binding_error("observation_shape_mismatch", "reentrant observation poisoned the binding");
    auto state = encode_counter_observation(observation);
    ++runtime->counts.at(stable_action);
    runtime->running = false;
    return state;
    } catch (const BindingError&) {
      runtime->lifecycle = Lifecycle::poisoned;
      runtime->running = false;
      if (stage == Stage::dispatch || stage == Stage::input) throw;
      throw binding_error(stage == Stage::observation ? "observation_shape_mismatch" : "adapter_failure", "binding callback failed");
    } catch (const std::exception& error) {
      runtime->lifecycle = Lifecycle::poisoned;
      runtime->running = false;
      const std::string code = stage == Stage::input ? "input_shape_mismatch" : stage == Stage::observation ? "observation_shape_mismatch" : "adapter_failure";
      throw binding_error(code, error.what());
    } catch (...) {
      runtime->lifecycle = Lifecycle::poisoned;
      runtime->running = false;
      throw binding_error(stage == Stage::observation ? "observation_shape_mismatch" : "adapter_failure", "unknown binding failure");
    }
  };
  return {
    std::move(computer),
    [runtime] { return runtime->counts; },
    [runtime] {
      for (const auto& [id, count] : runtime->counts) if (count == 0) throw std::runtime_error("uncovered action: " + id);
    },
  };
}

}  // namespace mirrors_generated::counter
